### ISSUE TITLE
Crashes due to having no code for numpad

### ISSUE THREAD

**Issue by Thewisem** [dslul/openboard#279]
I have had a crash where the app crashed due to not having a number pad. I would advise to make a keyboard along with the original keyboard which had numbers and signs only. Because some apps will ask for that specific number pad. Some apps only request numbers and not letters. So this would be helpful
:)

**Comment by jnnkB** [comment]
By numpad do mean this?
![IMG_20210316_130508](https://user-images.githubusercontent.com/29376715/111306310-58cce880-8658-11eb-824d-e0f587b44a9f.jpg)
Because it seems to exist…

**Comment by ndts55** [comment]
This has been fixed, hasn't it?

**Comment by ndts55** [comment]
@Thewisem , can you reproduce the bug? If so, can you describe how to do so?

**Comment by Thewisem** [comment]
Really

**Comment by Thewisem** [comment]
Mind explaining this?

**Comment by Thewisem** [comment]
![Screenshot_20210403-195144](https://user-images.githubusercontent.com/74511929/113485498-743c4e00-94b6-11eb-83ce-66c2bc5cf252.jpg)
![Screenshot_20210403-195124](https://user-images.githubusercontent.com/74511929/113485503-79999880-94b6-11eb-94df-ea566d94f43f.jpg)

**Comment by Thewisem** [comment]
This was a situation which required a numpad

**Comment by Thewisem** [comment]
And yet it crashed

**Comment by Thewisem** [comment]
That black screen was what occured when i cliked on that verification bar. Then I went to google and clicked on that bar and it went back to normal. After going to that bar, I went back to this bar and clicked. It stopped working. I think your numpad doesn't adjust to landscape mode and crashes.

**Comment by NoahAndrews** [comment]
No need to have a hostile tone. They just pointed out that in some circumstances the numpad works fine, and asked how to reproduce the issue. No one accused you of lying.

**Comment by Thewisem** [comment]
Oh dame, did I came off as that. Sorry, dame didn't want to tone it that way. I wanted to come off as someone who was just curious. I thought I only had the problem. So I thought they might have had an explanation. Sorry Sorry if it came off as being rude. Really didn't want that impact.

**Comment by Thewisem** [comment]
I said really for the second comment ao as to suggest whether that was the case. It came off after third comment because I didn't have a situation where I needed to use it. :( .

**Comment by Thewisem** [comment]
I only put my guess on why and I have no clue. I just put an opinion and guessed. Hope this helps :)

**Comment by Thewisem** [comment]
> By numpad do mean this?
> ![IMG_20210316_130508](https://user-images.githubusercontent.com/29376715/111306310-58cce880-8658-11eb-824d-e0f587b44a9f.jpg)
> Because it seems to exist…

Sorry I wanted to continue from this

**Comment by NoahAndrews** [comment]
No worries, I'm glad you didn't mean it that way. 

As you can see, that works fine for me.
![Screenshot_20210403-131302.png](https://user-images.githubusercontent.com/10224994/113487556-6539a980-947e-11eb-9a49-39dc39701aaf.png)

What Android device, version, and web browser are you using?

**Comment by Thewisem** [comment]
Hmmm see my comment. Try doing that in landscape mode

**Comment by Thewisem** [comment]
I think it isn't working in landscape mode

**Comment by NoahAndrews** [comment]
![Screenshot_20210403-132415.png](https://user-images.githubusercontent.com/10224994/113487820-d9c11800-947f-11eb-99a1-34610437cf3b.png)

I promise you that it's far more likely to be an incompatibility between OpenBoard and your specific version of Android and/or the browser.

**Comment by Thewisem** [comment]
Hmmm Ok.
Device: Samsung Galaxy Tab A SM P555.
OS: Android 7.1.1 Nougat
Rooted: No
Orientation: Landscape
Browser: Bromite latest version

**Comment by Thewisem** [comment]
Unfortunately, I can't give crash reports as it doesn't have a craah reporting function like newpipe.

**Comment by jnnkB** [comment]
If you want to try imvestigating further you could try finding something relevant in the Logs using some tool like [SysLog](https://f-droid.org/packages/com.tortel.syslog). But I'm no expert and I don't know how this app works internally so you might find nothing at all.

**Comment by NoahAndrews** [comment]
The most helpful debugging data you can gather is probably the Logcat logs (run `adb logcat` (you'll have to download the Android Platform Tools), then cause the crash, and then see what Logcat printed.

**Comment by Thewisem** [comment]
Uhhhhhhh

**Comment by Thewisem** [comment]
I don't have a computer

**Comment by jnnkB** [comment]
You could still try using [SysLog](https://f-droid.org/packages/com.tortel.syslog) since its simply an android app. It also contains the logcat.

**Comment by NoahAndrews** [comment]
That app needs a special permission though... which you grant from a computer using adb.

**Comment by jnnkB** [comment]
Oh Ok. Didn't know that.

**Comment by dslul** [comment]
I can confirm this bug, I managed to reproduce it on an old nexus 7. It seems to be an issue with themes, the old holo white and blue work correctly.

**Comment by dslul** [comment]
fixed 6796bd88bd8d06ab9ce147aabdedde2faa415390. @Thewisem Sorry for taking so long.

**Comment by Thewisem** [comment]
No worries. Happy to help. Thankful that you noticed my problem. :). Will comment whether I find it working.

**Comment by Thewisem** [comment]
When you update the app, please do tell. I will be happy to test it out. Thanks for fixing my issue

**Comment by phatpaul** [comment]
My openboard is crashing when trying to pair to a BluetoothLE device which requires entry of a 6-digit PIN.  I'm guessing it's related to this bug, so I'm not opening a new ticket.  Is this fix included in a release yet?   I just updated to version 1.4.3 on F-droid, but it didn't fix the problem.

**Comment by jnnkB** [comment]
AFAIK it's not included in any release yet. So you'll probably have to wait until the next release.

**Comment by Thewisem** [comment]
Yeah still not fixed

**Comment by Thewisem** [comment]
![Screenshot_20210610-222759](https://user-images.githubusercontent.com/74511929/121585360-2a825d80-ca3b-11eb-88eb-94a5943a2a16.jpg)

**Comment by Thewisem** [comment]
Reopen this thread. Cause it isn't fixed. I forgot but thanks to your comment I checked it out. It still isn't working

**Comment by jnnkB** [comment]
Since @dslul already fixed it in the code and just didn't release a new version yet I think we can leave this issue closed. Or did you test it by compiling from source?

**Comment by dslul** [comment]
I haven't pushed the update yet, I'll try to do it this weekend.
